"""Static regression guards for the five approved routing/consistency fixes.

Structural only. These tests parse real frontmatter / JSON / generated SVG and
compare generated bytes; they never execute a model, a browser or the live PDCA
cycle. They therefore prove structure, not agent behavior.

Run:
    PYTHONDONTWRITEBYTECODE=1 python3 -m unittest discover \
        -s config/skills/pdca-dotnet/tests -p test_routing_consistency.py -v
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path

REPO = Path(__file__).resolve().parents[4]
SKILL = REPO / "config/skills/pdca-dotnet/SKILL.md"
DIAGRAM = REPO / "config/skills/pdca-dotnet/assets/diagram"
GEN = DIAGRAM / "gen_pdca.py"
WORKFLOW = DIAGRAM / "workflow.json"
OUTPUTS = ["pdca-hand.svg", "pdca-hand.html", "pdca-hand-dark.svg", "pdca-hand-dark.html"]
CONFIG_AGENTS = "config/agents"
ASSET_AGENTS = "config/skills/pdca-dotnet/assets/agents"
TIERS = {
    "architect": "medium", "planner": "medium", "coder": "cheap", "check": "medium",
    "escalate": "strong", "scout": "cheap", "security-auditor": "medium",
    # The cheap orchestrator was renamed lane -> pdca-orchestrator; only the
    # canonical name is accepted (a legacy fallback would hide stale routing).
    "pdca-orchestrator": "cheap",
}
ORCHESTRATOR = REPO / f"{CONFIG_AGENTS}/pdca-orchestrator.md"
LEGACY_ORCHESTRATOR = REPO / f"{CONFIG_AGENTS}/lane.md"
PROFILES = ["config/profiles/deepseek.jsonc", "config/profiles/gp.jsonc"]
# Required permission subtrees that must mirror config/agents <-> assets/agents.
MIRROR = {
    "planner": ["*"], "check": ["*"], "coder": ["edit", "bash"],
    "escalate": ["*", "read", "task", "bash", "skill"],
    "security-auditor": ["*", "read", "task", "bash", "skill"],
}
SEC_SKILLS = {"dotnet-security-owasp", "dotnet-secrets-management", "dotnet-cryptography"}
CRITICAL_TOKENS = [
    "Execute an escalate decision by routing, never by re-deciding",
    "cannot waive the gates, the no-4th rule",
    "there is no 4th",
    "Cheap primary only",
    "effective host-profile tier is cheap",
    "medium/strong primary (e.g. architect) does not drive the cycle",
    "returns into the aggregated report",
    "ordinary security finding is an ordinary failed stream",
    "hard security trade-off",
]


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def norm(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("`", "").replace("*", "")).strip()


def _parse_block(block: str) -> dict:
    """Tiny indentation parser for the flat/sub-map frontmatter subset used here."""
    root: dict = {}
    stack: list[tuple[int, dict]] = [(-1, root)]
    for raw in block.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        key, _, val = raw.strip().partition(":")
        key, val = key.strip().strip('"').strip("'"), val.strip().strip('"').strip("'")
        while stack and indent <= stack[-1][0]:
            stack.pop()
        if val == "":
            stack[-1][1][key] = {}
            stack.append((indent, stack[-1][1][key]))
        else:
            stack[-1][1][key] = val
    return root


def frontmatter(path: Path) -> dict:
    text = read(path)
    assert text.startswith("---"), f"{path}: no frontmatter"
    return _parse_block(text[3:text.find("\n---", 3)])


def permission(path: Path) -> dict:
    return frontmatter(path).get("permission", {})


def allow_keys(node: dict) -> set:
    return {k for k, v in node.items() if v == "allow"}


def _agent_block(text: str) -> str:
    """Raw text of a jsonc profile's top-level `agent` sub-map (comments tolerated)."""
    match = re.search(r'"agent"\s*:\s*\{(.*?)\n\s*\}', text, re.S)
    if match is None:
        raise AssertionError("no top-level agent block in profile")
    return match.group(1)


class RolePermissionTest(unittest.TestCase):
    """Cheap orchestrator canonical allowlist; expensive roles stay narrow and mirror the assets."""

    def test_cheap_orchestrator_canonical_task_allowlist(self):
        self.assertTrue(ORCHESTRATOR.exists(), "canonical pdca-orchestrator agent missing")
        self.assertRegex(read(ORCHESTRATOR), r"(?m)^# tier: cheap\s*$")
        perm = permission(ORCHESTRATOR)
        self.assertEqual(perm["task"]["*"], "deny")
        self.assertEqual(
            allow_keys(perm["task"]),
            {"planner", "coder", "check", "escalate", "scout", "security-auditor",
             "docfx-specialist", "dotnet-*",
             "pdca-planner", "pdca-executor", "pdca-check", "pdca-escalate"},
        )
        self.assertEqual(perm.get("edit"), "deny")
        self.assertEqual(perm.get("bash"), "deny")

    def test_orchestrator_description_covers_single_autonomous_cycle_no_single_tasks_ban(self):
        # The description advertises BOTH inputs -- a pdca-collection group *or* a
        # single autonomous pdca-dotnet cycle -- and must not ban single tasks. The
        # canonical task allowlist and edit/bash: deny are pinned by
        # test_cheap_orchestrator_canonical_task_allowlist above.
        desc = norm(frontmatter(ORCHESTRATOR).get("description", "")).lower()
        self.assertTrue(desc, "pdca-orchestrator description missing")
        self.assertIn("single autonomous", desc)
        self.assertIn("pdca-dotnet", desc)
        self.assertIn("task", desc)
        self.assertNotIn("do not use for single tasks", desc)

    def test_legacy_lane_agent_definition_is_absent(self):
        # The cheap orchestrator was renamed; a lingering lane.md would mean stale
        # routing is still discoverable.
        self.assertFalse(
            LEGACY_ORCHESTRATOR.exists(),
            "legacy config/agents/lane.md must not exist (renamed to pdca-orchestrator)",
        )

    def test_profiles_bind_canonical_orchestrator_not_legacy_lane(self):
        # Model ids are host-profile concerns; only the registry key is asserted.
        for rel in PROFILES:
            with self.subTest(profile=rel):
                agent = _agent_block(read(REPO / rel))
                self.assertIn('"pdca-orchestrator"', agent)
                self.assertNotIn('"lane"', agent)

    def test_architect_task_allowlist_is_default_deny_scout_and_coder_only(self):
        perm = permission(REPO / f"{CONFIG_AGENTS}/architect.md")
        self.assertEqual(perm["*"], "deny")
        self.assertEqual(perm["task"]["*"], "deny")
        allowed = allow_keys(perm["task"])
        self.assertEqual(allowed, {"scout", "coder"})
        self.assertFalse({k for k in allowed if k.startswith("dotnet")})
        self.assertNotIn("security-auditor", allowed)
        for wide in ("read", "bash", "edit"):
            self.assertNotIn(wide, perm)

    def test_planner_and_check_have_no_task_permission(self):
        for role in ("planner", "check"):
            for base in (CONFIG_AGENTS, ASSET_AGENTS):
                with self.subTest(role=role, base=base):
                    perm = permission(REPO / base / f"{role}.md")
                    self.assertEqual(perm["*"], "deny")
                    self.assertNotIn("task", perm)

    def test_escalate_task_only_scout(self):
        for base in (CONFIG_AGENTS, ASSET_AGENTS):
            with self.subTest(base=base):
                perm = permission(REPO / base / "escalate.md")
                self.assertEqual(perm["task"]["*"], "deny")
                self.assertEqual(allow_keys(perm["task"]), {"scout"})

    def test_security_auditor_allows_exactly_three_skills(self):
        for base in (CONFIG_AGENTS, ASSET_AGENTS):
            with self.subTest(base=base):
                perm = permission(REPO / base / "security-auditor.md")
                self.assertEqual(perm["skill"]["*"], "deny")
                self.assertEqual(allow_keys(perm["skill"]), SEC_SKILLS)

    def test_required_permissions_mirror_config_and_asset(self):
        for role, keys in MIRROR.items():
            cfg = permission(REPO / f"{CONFIG_AGENTS}/{role}.md")
            asset = permission(REPO / f"{ASSET_AGENTS}/{role}.md")
            for key in keys:
                with self.subTest(role=role, key=key):
                    self.assertIn(key, cfg)
                    self.assertEqual(cfg[key], asset.get(key))

    def test_all_role_tiers_are_tier_comments(self):
        for name, tier in TIERS.items():
            paths = [REPO / f"{CONFIG_AGENTS}/{name}.md", REPO / f"{ASSET_AGENTS}/{name}.md"]
            for path in filter(Path.exists, paths):
                with self.subTest(path=str(path.relative_to(REPO))):
                    self.assertRegex(read(path), rf"(?m)^# tier: {tier}\s*$")
                    self.assertNotRegex(read(path), r"(?m)^\s*#\s*model:")


class WorkflowContractTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        data = json.loads(read(WORKFLOW))
        cls.nodes = {n["id"]: n for n in data["nodes"]}
        cls.edges = {e["id"]: e for e in data["edges"]}

    def test_security_fork_and_report_return_to_check(self):
        fork = self.edges["e_sec_audit"]
        self.assertEqual((fork["from"], fork["to"]), ("check", "sec_audit"))
        report = self.edges["e_sec_report"]
        self.assertEqual((report["from"], report["to"]), ("sec_audit", "check"))
        self.assertIn("условно", fork["label"])
        self.assertIn("отчёт", report["label"])
        self.assertIn("агрегац", report["label"])

    def test_lenses_edge_to_act_requires_all_four_plus_security(self):
        edge = self.edges["e_lenses"]
        self.assertEqual((edge["from"], edge["to"]), ("check", "act"))
        for token in ("4", "security", "final CHECK"):
            self.assertIn(token, edge["label"])

    def test_escalate_to_orchestrator_is_a_decision_not_a_recommendation(self):
        edge = self.edges["e_escalate_orb"]
        self.assertEqual((edge["from"], edge["to"]), ("escalate", "orb"))
        self.assertIn("решение", edge["label"])
        self.assertNotIn("рекоменд", edge["label"])

    def test_orchestrator_routes_conditionally_and_never_to_act(self):
        do, replan = self.edges["e_orb_do"], self.edges["e_orb_replan"]
        self.assertEqual((do["from"], do["to"]), ("orb", "do"))
        self.assertIn("не исчерпан", do["label"])
        self.assertEqual((replan["from"], replan["to"]), ("orb", "plan"))
        self.assertIn("исчерпан", replan["label"])
        self.assertIn("r+1", replan["label"])
        self.assertEqual(
            (self.edges["e_orb_stop"]["from"], self.edges["e_orb_stop"]["to"]), ("orb", "stop"))
        self.assertNotIn("e_orb_act", self.edges)
        self.assertEqual({e["from"] for e in self.edges.values() if e["to"] == "act"}, {"check"})


def _direction(root, edge_id: str) -> tuple:
    """Source/target from data-from/to when present, else from endpoint geometry."""
    edge = next(el for el in root.iter() if el.get("data-edge-id") == edge_id)
    if edge.get("data-from") and edge.get("data-to"):
        return edge.get("data-from"), edge.get("data-to")
    boxes = {}
    for el in root.iter():
        nid = el.get("data-node-id")
        if nid:
            boxes[nid] = tuple(float(el.get(a) or 0) for a in ("x", "y", "width", "height"))
    pts = [(float(a), float(b))
           for a, b in (p.split(",") for p in (edge.get("points") or "").split())]

    def dist(p, b) -> float:
        x, y, w, h = b
        return ((max(x - p[0], 0, p[0] - (x + w))) ** 2
                + (max(y - p[1], 0, p[1] - (y + h))) ** 2) ** 0.5

    nearest = lambda p: min(boxes, key=lambda n: dist(p, boxes[n]))
    return nearest(pts[0]), nearest(pts[-1])


class GeneratedDiagramTest(unittest.TestCase):
    """Freshness/determinism + structural selectors on freshly rendered SVG."""

    @classmethod
    def setUpClass(cls) -> None:
        env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
        cls.dirs, cls.runs = [], []
        for _ in range(2):
            tmp = tempfile.TemporaryDirectory()
            shutil.copy(GEN, tmp.name)
            subprocess.run([sys.executable, "gen_pdca.py"], cwd=tmp.name, env=env, check=True,
                           capture_output=True, text=True)
            cls.dirs.append(tmp)
            cls.runs.append({n: (Path(tmp.name) / n).read_bytes() for n in OUTPUTS})

    @classmethod
    def tearDownClass(cls) -> None:
        for tmp in cls.dirs:
            tmp.cleanup()

    def test_generator_outputs_four_files_matching_assets(self):
        self.assertEqual(set(self.runs[0]), set(OUTPUTS))
        for name in OUTPUTS:
            with self.subTest(name=name):
                self.assertEqual(self.runs[0][name], (DIAGRAM / name).read_bytes())

    def test_generator_is_deterministic_across_runs(self):
        for name in OUTPUTS:
            with self.subTest(name=name):
                self.assertEqual(self.runs[0][name], self.runs[1][name])

    def test_named_edges_and_nodes_present_in_both_themes(self):
        expected_edges = {
            "check_security", "security_check_report", "security_escalate_tradeoff",
            "escalate_do_nonexhausted", "escalate_plan_exhausted", "escalate_stop", "check_act",
        }
        expected_nodes = {"PLAN", "DO", "CHECK", "ACT", "START", "EXIT",
                          "sec_check", "escalate", "stop"}
        for svg in ("pdca-hand.svg", "pdca-hand-dark.svg"):
            root = ET.fromstring(self.runs[0][svg])
            with self.subTest(svg=svg):
                edges = {el.get("data-edge-id") for el in root.iter() if el.get("data-edge-id")}
                nodes = {el.get("data-node-id") for el in root.iter() if el.get("data-node-id")}
                self.assertTrue(expected_edges <= edges)
                self.assertTrue(expected_nodes <= nodes)

    def test_svg_edge_directions_security_and_escalation(self):
        root = ET.fromstring(self.runs[0]["pdca-hand.svg"])
        expected = {
            "check_security": ("CHECK", "sec_check"),
            "security_check_report": ("sec_check", "CHECK"),
            "security_escalate_tradeoff": ("sec_check", "escalate"),
            "escalate_do_nonexhausted": ("escalate", "DO"),
            "escalate_plan_exhausted": ("escalate", "PLAN"),
            "escalate_stop": ("escalate", "stop"),
            "check_act": ("CHECK", "ACT"),
        }
        for edge_id, pair in expected.items():
            with self.subTest(edge=edge_id):
                self.assertEqual(_direction(root, edge_id), pair)

    def test_svg_condition_and_tradeoff_labels(self):
        for svg in ("pdca-hand.svg", "pdca-hand-dark.svg"):
            root = ET.fromstring(self.runs[0][svg])
            texts = " ".join(el.text or "" for el in root.iter() if el.tag.endswith("text"))
            with self.subTest(svg=svg):
                for token in ("не исчерпан", "исчерпан r", "r+1", "tradeoff"):
                    self.assertIn(token, texts)

    def test_html_inlines_paired_svg_module_for_module(self):
        for html_name, svg_name in (("pdca-hand.html", "pdca-hand.svg"),
                                    ("pdca-hand-dark.html", "pdca-hand-dark.svg")):
            html = self.runs[0][html_name].decode("utf-8")
            match = re.search(r"<svg\b.*?</svg>", html, re.S)
            with self.subTest(html=html_name):
                self.assertEqual(html.count("<svg"), 1)
                if match is None:
                    self.fail("inline SVG not found")
                self.assertEqual(match.group(0).strip(),
                                 (DIAGRAM / svg_name).read_text(encoding="utf-8").strip())


class ContractTextTest(unittest.TestCase):
    def test_skill_critical_routing_tokens(self):
        skill = norm(read(SKILL))
        missing = [token for token in CRITICAL_TOKENS if token not in skill]
        self.assertEqual(missing, [])


if __name__ == "__main__":
    unittest.main()
